### 0307 variables 변수

1. int: 정수

2. float: 실수

3. str: string text
->string type 을 list로 바꾸면 쪼개진다 ("123"->"1" "2" "3")

In [17]:
a = 1; print(type(a))

<class 'int'>


In [18]:
a = 1; a = float(a); print(type(a))

<class 'float'>


In [19]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


In [6]:
a= "string"
a = list(a)
print(a)
print(a[3])

['s', 't', 'r', 'i', 'n', 'g']
i


### 0314 variables 변수

1. [list]와 (tuple): 나열

2. {dict}= {"a": "apple"} 

In [2]:
a= {"1": "Seoul", "2": "Korea", "3": "Yonsei"}
print(type(a))
print(a["1"])

<class 'dict'>
Seoul


In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


3. 행렬과 numpy, import

In [27]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

tuple 두개가 들어있는 list는 2*3의 행렬

하지만 행렬의 형태로 쓰기 위해서는 numpy라는 package를 import해와야 함

In [28]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


numpy를 np로 지정한 뒤 

b=np.array(a)   ->b를 numpy(=np)아래에서 array 한 것 (np. 이거 꼭 넣어야함)

class- numpy가 제공하는 nd array

하지만 완전한 array는 행렬은 아니기 때문에 (2x3)(2x3)같은 불가능한 계산도 (2*3)으로가능

In [3]:
a = [(1, 3, 5), (2, 4, 6)]
import numpy as np
b = np.array(a)
print(type(b))
print(b)

<class 'numpy.ndarray'>
[[1 3 5]
 [2 4 6]]


In [29]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


np.matrix로 진짜 행렬로 만듬

In [4]:
c= np.matrix(b)
print(type(c))
print(c)

<class 'numpy.matrixlib.defmatrix.matrix'>
[[1 3 5]
 [2 4 6]]


In [30]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [31]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])

t=transpose. 2*3 3*2 로 만들어서 2*2 가 됨